# Generated by Django 2.1.8 on 2019-05-31 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('PersonaId', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=200)),
                ('apellidoPaterno', models.CharField(max_length=200)),
                ('apellidoMaterno', models.CharField(max_length=200)),
                ('nombres', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
                ('FechaCreacion', models.DateField(auto_now=True, verbose_name='fecha de creacion')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['dni'],
            },
        ),
    ]
